extends:
  - airbnb-base
  - plugin:ava/recommended

parserOptions:
  ecmaVersion: 2020
  sourceType: module

env:
  node: true

plugins:
  - ava
  - import

rules:
  no-underscore-dangle: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  import/extensions:
    - error
    - always
    - ignorePackages: true
